# coding=utf-8
from otlmow_model.OtlmowModel.BaseClasses.KeuzelijstField import KeuzelijstField
from otlmow_model.OtlmowModel.BaseClasses.KeuzelijstWaarde import KeuzelijstWaarde


# Generated with OTLEnumerationCreator. To modify: extend, do not edit
class KlBeschermbuisKleur(KeuzelijstField):
    """De kleur van de beschermbuis."""
    naam = 'KlBeschermbuisKleur'
    label = 'Beschermbuiskleur'
    objectUri = 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KlBeschermbuisKleur'
    definition = 'De kleur van de beschermbuis.'
    status = 'https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik'
    codelist = 'https://wegenenverkeer.data.vlaanderen.be/id/conceptscheme/KlBeschermbuisKleur'
    options = {
        '17': KeuzelijstWaarde(invulwaarde='17',
                               label='17',
                               status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/uitgebruik',
                               definitie='17',
                               objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/17'),
        '28': KeuzelijstWaarde(invulwaarde='28',
                               label='28',
                               status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/uitgebruik',
                               definitie='28',
                               objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/28'),
        'beb': KeuzelijstWaarde(invulwaarde='beb',
                                label='beb',
                                status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                definitie='beb',
                                objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/beb'),
        'blauw': KeuzelijstWaarde(invulwaarde='blauw',
                                  label='blauw',
                                  status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                  definitie='blauw',
                                  objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/blauw'),
        'blauw-geel': KeuzelijstWaarde(invulwaarde='blauw-geel',
                                       label='blauw-geel',
                                       status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                       definitie='blauw-geel',
                                       objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/blauw-geel'),
        'blauw-met-gele-streep': KeuzelijstWaarde(invulwaarde='blauw-met-gele-streep',
                                                  label='blauw-met-gele-streep',
                                                  status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                                  definitie='blauw-met-gele-streep',
                                                  objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/blauw-met-gele-streep'),
        'driekleur': KeuzelijstWaarde(invulwaarde='driekleur',
                                      label='driekleur',
                                      status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                      definitie='driekleur',
                                      objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/driekleur'),
        'geel': KeuzelijstWaarde(invulwaarde='geel',
                                 label='geel',
                                 status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                 definitie='geel',
                                 objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/geel'),
        'glasvezelbuis': KeuzelijstWaarde(invulwaarde='glasvezelbuis',
                                          label='glasvezelbuis',
                                          status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                          definitie='glasvezelbuis',
                                          objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/glasvezelbuis'),
        'grijs': KeuzelijstWaarde(invulwaarde='grijs',
                                  label='grijs',
                                  status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                  definitie='grijs',
                                  objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/grijs'),
        'groen': KeuzelijstWaarde(invulwaarde='groen',
                                  label='groen',
                                  status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                  definitie='groen',
                                  objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/groen'),
        'multi': KeuzelijstWaarde(invulwaarde='multi',
                                  label='multi',
                                  status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                  definitie='multi',
                                  objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/multi'),
        'onbekend': KeuzelijstWaarde(invulwaarde='onbekend',
                                     label='onbekend',
                                     status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                     definitie='onbekend',
                                     objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/onbekend'),
        'oranje': KeuzelijstWaarde(invulwaarde='oranje',
                                   label='oranje',
                                   status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                   definitie='oranje',
                                   objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/oranje'),
        'patchkoord': KeuzelijstWaarde(invulwaarde='patchkoord',
                                       label='patchkoord',
                                       status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                       definitie='patchkoord',
                                       objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/patchkoord'),
        'rood': KeuzelijstWaarde(invulwaarde='rood',
                                 label='rood',
                                 status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                 definitie='rood',
                                 objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/rood'),
        'rvs': KeuzelijstWaarde(invulwaarde='rvs',
                                label='rvs',
                                status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                definitie='rvs',
                                objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/rvs'),
        'zwart': KeuzelijstWaarde(invulwaarde='zwart',
                                  label='zwart',
                                  status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                  definitie='zwart',
                                  objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/zwart'),
        'zwart-met-groene-streep': KeuzelijstWaarde(invulwaarde='zwart-met-groene-streep',
                                                    label='zwart-met-groene-streep',
                                                    status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                                    definitie='zwart-met-groene-streep',
                                                    objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/zwart-met-groene-streep'),
        'zwart-met-rode-streep': KeuzelijstWaarde(invulwaarde='zwart-met-rode-streep',
                                                  label='zwart-met-rode-streep',
                                                  status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                                  definitie='zwart-met-rode-streep',
                                                  objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlBeschermbuisKleur/zwart-met-rode-streep')
    }

    @classmethod
    def create_dummy_data(cls):
        return cls.create_dummy_data_keuzelijst(cls.options)

