# coding=utf-8
from otlmow_model.OtlmowModel.BaseClasses.KeuzelijstField import KeuzelijstField
from otlmow_model.OtlmowModel.BaseClasses.KeuzelijstWaarde import KeuzelijstWaarde


# Generated with OTLEnumerationCreator. To modify: extend, do not edit
class KlWeergegevenVervoersmodiOpKaart(KeuzelijstField):
    """De verschillende beschikbare vervoersmodi die op de bijhorende kaart worden meegegeven."""
    naam = 'KlWeergegevenVervoersmodiOpKaart'
    label = 'Weergegeven vervoersmodi op kaart'
    objectUri = 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KlWeergegevenVervoersmodiOpKaart'
    definition = 'De verschillende beschikbare vervoersmodi die op de bijhorende kaart worden meegegeven.'
    status = 'https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik'
    codelist = 'https://wegenenverkeer.data.vlaanderen.be/id/conceptscheme/KlWeergegevenVervoersmodiOpKaart'
    options = {
        'bus': KeuzelijstWaarde(invulwaarde='bus',
                                label='Bus',
                                status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                definitie='Bus',
                                objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/bus'),
        'deelauto': KeuzelijstWaarde(invulwaarde='deelauto',
                                     label='Deelauto',
                                     status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                     definitie='TODO',
                                     objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/deelauto'),
        'deelbakfiets': KeuzelijstWaarde(invulwaarde='deelbakfiets',
                                         label='Deelbakfiets',
                                         status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                         definitie='Deelbakfiets',
                                         objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/deelbakfiets'),
        'deelbolderkar': KeuzelijstWaarde(invulwaarde='deelbolderkar',
                                          label='Deelbolderkar',
                                          status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                          definitie='Deelbolderkar',
                                          objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/deelbolderkar'),
        'deelbuggy': KeuzelijstWaarde(invulwaarde='deelbuggy',
                                      label='Deelbuggy',
                                      status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                      definitie='Deelbuggy',
                                      objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/deelbuggy'),
        'deelfiets': KeuzelijstWaarde(invulwaarde='deelfiets',
                                      label='Deelfiets',
                                      status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                      definitie='TODO',
                                      objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/deelfiets'),
        'deelrolstoel': KeuzelijstWaarde(invulwaarde='deelrolstoel',
                                         label='Deelrolstoel',
                                         status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                         definitie='Deelrolstoel',
                                         objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/deelrolstoel'),
        'deelstep': KeuzelijstWaarde(invulwaarde='deelstep',
                                     label='Deelstep',
                                     status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                     definitie='Deelstep',
                                     objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/deelstep'),
        'deelwagen': KeuzelijstWaarde(invulwaarde='deelwagen',
                                      label='Deelwagen',
                                      status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                      definitie='Deelwagen',
                                      objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/deelwagen'),
        'e-deelbakfiets': KeuzelijstWaarde(invulwaarde='e-deelbakfiets',
                                           label='e-deelbakfiets',
                                           status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                           definitie='e-deelbakfiets',
                                           objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/e-deelbakfiets'),
        'e-deelfiets': KeuzelijstWaarde(invulwaarde='e-deelfiets',
                                        label='e-deelfiets',
                                        status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                        definitie='e-deelfiets',
                                        objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/e-deelfiets'),
        'e-deelstep': KeuzelijstWaarde(invulwaarde='e-deelstep',
                                       label='e-deelstep',
                                       status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                       definitie='e-deelstep',
                                       objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/e-deelstep'),
        'e-deelwagen': KeuzelijstWaarde(invulwaarde='e-deelwagen',
                                        label='e-deelwagen',
                                        status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                        definitie='e-deelwagen',
                                        objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/e-deelwagen'),
        'flex': KeuzelijstWaarde(invulwaarde='flex',
                                 label='Flex',
                                 status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                 definitie='Flex',
                                 objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/flex'),
        'flex-2': KeuzelijstWaarde(invulwaarde='flex-2',
                                   label='Flex+',
                                   status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                   definitie='Flex+',
                                   objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/flex-2'),
        'flexvervoer': KeuzelijstWaarde(invulwaarde='flexvervoer',
                                        label='Flexvervoer',
                                        status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                        definitie='TODO',
                                        objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/flexvervoer'),
        'kernnet-aanvullend-net': KeuzelijstWaarde(invulwaarde='kernnet-aanvullend-net',
                                                   label='Kernnet - aanvullend net',
                                                   status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                                   definitie='TODO',
                                                   objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/kernnet-aanvullend-net'),
        'metro': KeuzelijstWaarde(invulwaarde='metro',
                                  label='Metro',
                                  status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                  definitie='Metro',
                                  objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/metro'),
        'taxi': KeuzelijstWaarde(invulwaarde='taxi',
                                 label='Taxi',
                                 status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                 definitie='Taxi',
                                 objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/taxi'),
        'tram': KeuzelijstWaarde(invulwaarde='tram',
                                 label='Tram',
                                 status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                 definitie='Tram',
                                 objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/tram'),
        'trein': KeuzelijstWaarde(invulwaarde='trein',
                                  label='Trein',
                                  status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                  definitie='Trein',
                                  objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/trein'),
        'treinnet': KeuzelijstWaarde(invulwaarde='treinnet',
                                     label='Treinnet',
                                     status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                     definitie='TODO',
                                     objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/treinnet'),
        'vast-en-semiflex': KeuzelijstWaarde(invulwaarde='vast-en-semiflex',
                                             label='Vast en semiflex',
                                             status='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlAdmsStatus/ingebruik',
                                             definitie='TODO',
                                             objectUri='https://wegenenverkeer-test.data.vlaanderen.be/id/concept/KlWeergegevenVervoersmodiOpKaart/vast-en-semiflex')
    }

    @classmethod
    def create_dummy_data(cls):
        return cls.create_dummy_data_keuzelijst(cls.options)

